create or replace PROCEDURE ADD_STATUS (
    p_STATUS IN VARCHAR2,
    p_DESCRIPTION IN CLOB
) AS
BEGIN
    INSERT INTO STATUSES (ID, STATUS, DESCRIPTION, CREATED_AT, UPDATED_AT)
    VALUES (STATUSES_ID_SEQ.NEXTVAL, p_STATUS, p_DESCRIPTION, SYSTIMESTAMP, SYSTIMESTAMP);
END ADD_STATUS;
/
create or replace PROCEDURE DELETE_STATUS (
    p_ID IN NUMBER
) AS
BEGIN
    DELETE FROM STATUSES
    WHERE ID = p_ID;
END DELETE_STATUS;
/
create or replace PROCEDURE GET_STATUS (
    p_ID IN NUMBER,
    p_status OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_status FOR
    SELECT STATUS, DESCRIPTION
    FROM STATUSES
    WHERE ID = p_ID;
END GET_STATUS;
/
create or replace PROCEDURE UPDATE_STATUS (
    p_ID IN NUMBER,
    p_STATUS IN VARCHAR2,
    p_DESCRIPTION IN CLOB
) AS
BEGIN
    UPDATE STATUSES
    SET STATUS = p_STATUS,
        DESCRIPTION = p_DESCRIPTION
    WHERE ID = p_ID;
END UPDATE_STATUS;
/