create or replace PROCEDURE ADD_TREATMENT_TYPE (
    p_NAME IN VARCHAR2,
    p_DESCRIPTION IN CLOB,
    p_RECOMMENDATIONS_BEFORE_SURGERY IN CLOB,
    p_RECOMMENDATIONS_AFTER_SURGERY IN CLOB
) AS
BEGIN
    INSERT INTO TREATMENT_TYPES (ID,"NAME", "DESCRIPTION", "RECOMMENDATIONS_BEFORE_SURGERY", "RECOMMENDATIONS_AFTER_SURGERY")
    VALUES (TREATMENT_TYPES_ID_SEQ.NEXTVAL,p_NAME, p_DESCRIPTION, p_RECOMMENDATIONS_BEFORE_SURGERY, p_RECOMMENDATIONS_AFTER_SURGERY);
END;
/
create or replace PROCEDURE DELETE_TREATMENT_TYPE (
    p_ID IN NUMBER
) AS
BEGIN
    DELETE FROM TREATMENT_TYPES WHERE ID = p_ID;
END;
/
create or replace PROCEDURE GET_TREATMENT_TYPE (
    p_ID IN NUMBER,
    p_NAME OUT VARCHAR2,
    p_DESCRIPTION OUT CLOB,
    p_RECOMMENDATIONS_BEFORE_SURGERY OUT CLOB,
    p_RECOMMENDATIONS_AFTER_SURGERY OUT CLOB,
    p_CREATED_AT OUT TIMESTAMP,
    p_UPDATED_AT OUT TIMESTAMP
) AS
BEGIN
    SELECT NAME, DESCRIPTION, RECOMMENDATIONS_BEFORE_SURGERY, RECOMMENDATIONS_AFTER_SURGERY, CREATED_AT, UPDATED_AT
    INTO p_NAME, p_DESCRIPTION, p_RECOMMENDATIONS_BEFORE_SURGERY, p_RECOMMENDATIONS_AFTER_SURGERY, p_CREATED_AT, p_UPDATED_AT
    FROM TREATMENT_TYPES
    WHERE ID = p_ID;
END;
/
create or replace PROCEDURE UPDATE_TREATMENT_TYPE (
    p_ID IN NUMBER,
    p_NAME IN VARCHAR2,
    p_DESCRIPTION IN CLOB,
    p_RECOMMENDATIONS_BEFORE_SURGERY IN CLOB,
    p_RECOMMENDATIONS_AFTER_SURGERY IN CLOB
) AS
BEGIN
    UPDATE TREATMENT_TYPES
    SET NAME = p_NAME, DESCRIPTION = p_DESCRIPTION, RECOMMENDATIONS_BEFORE_SURGERY = p_RECOMMENDATIONS_AFTER_SURGERY,
        RECOMMENDATIONS_AFTER_SURGERY = p_RECOMMENDATIONS_AFTER_SURGERY
    WHERE ID = p_ID;
END;
/